language: python
dist: xenial
python:
  - "3.7"
install:
  - pip install -r requirements/dev.txt
before_script:
  - pip install coveralls PyYAML
script:
  - coverage run -m pytest tests
  - coveralls
